import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'
import Main from '../components/Main'


export const getStaticProps = async () => {
  const res = await fetch('https://top10-webhostings.com/cp/Api');
  const datas = await res.json();
  return {
    props : { datas }
  }
} 

export default function Home({datas}) {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main datas={datas}/>
    </div>
  )
}
